accessManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/access-manager-amd64
      tag: v0.26.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
addonController:
  controller:
    args:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --shard-key=
    - --v=5
    - --version=v0.25.0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --shard-key=
    - --v=5
    - --version=v0.26.0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/addon-controller-amd64
      tag: v0.26.0
  nodeSelector: {}
  replicas: 1
  tolerations: []
classifierManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --shard-key=
    - --v=5
    - --version=v0.25.0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --shard-key=
    - --v=5
    - --version=v0.26.0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/classifier-amd64
      tag: v0.26.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
eventManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/event-manager-amd64
      tag: v0.26.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
hcManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/healthcheck-manager-amd64
      tag: v0.26.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
kubernetesClusterDomain: cluster.local
scManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/sveltoscluster-manager-amd64
      tag: v0.26.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
shardController:
  manager:
    args:
    - --diagnostics-address=:8443
    - --v=5
    - --report-mode=0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/shard-controller-amd64
      tag: v0.26.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
prometheus:
  enabled: false
agent:
  managementCluster: false
